//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace _11_Image_Processing.Resources.Strings {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("_11_Image_Processing.Resources.Strings.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About.
        /// </summary>
        public static string About {
            get {
                return ResourceManager.GetString("About", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _AddBoxes.
        /// </summary>
        public static string AddBoxes {
            get {
                return ResourceManager.GetString("AddBoxes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Adding .
        /// </summary>
        public static string Adding {
            get {
                return ResourceManager.GetString("Adding", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add New.
        /// </summary>
        public static string AddNew {
            get {
                return ResourceManager.GetString("AddNew", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Advanced.
        /// </summary>
        public static string Advanced {
            get {
                return ResourceManager.GetString("Advanced", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All files.
        /// </summary>
        public static string Allfiles {
            get {
                return ResourceManager.GetString("Allfiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Alt (Hold).
        /// </summary>
        public static string AltHold {
            get {
                return ResourceManager.GetString("AltHold", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Answer.
        /// </summary>
        public static string Answer {
            get {
                return ResourceManager.GetString("Answer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Answer Box Color.
        /// </summary>
        public static string AnswerBoxColor {
            get {
                return ResourceManager.GetString("AnswerBoxColor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Answer Box Color 2.
        /// </summary>
        public static string AnswerBoxColor2 {
            get {
                return ResourceManager.GetString("AnswerBoxColor2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Answer Boxes.
        /// </summary>
        public static string AnswerBoxes {
            get {
                return ResourceManager.GetString("AnswerBoxes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Answer Field.
        /// </summary>
        public static string AnswerField {
            get {
                return ResourceManager.GetString("AnswerField", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Apply.
        /// </summary>
        public static string Apply {
            get {
                return ResourceManager.GetString("Apply", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Blank PDF File.
        /// </summary>
        public static string BlankPDFFile {
            get {
                return ResourceManager.GetString("BlankPDFFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bound Width.
        /// </summary>
        public static string BoundWidth {
            get {
                return ResourceManager.GetString("BoundWidth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Boxes.
        /// </summary>
        public static string Boxes {
            get {
                return ResourceManager.GetString("Boxes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Box Size.
        /// </summary>
        public static string BoxSize {
            get {
                return ResourceManager.GetString("BoxSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can not delete last page.
        /// </summary>
        public static string cannotDeleteLastPage {
            get {
                return ResourceManager.GetString("cannotDeleteLastPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can not edit document when locked.
        ///Unlock in overview..
        /// </summary>
        public static string Canteditwhenlocked {
            get {
                return ResourceManager.GetString("Canteditwhenlocked", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Checked.
        /// </summary>
        public static string Checked {
            get {
                return ResourceManager.GetString("Checked", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CHM.
        /// </summary>
        public static string CHM {
            get {
                return ResourceManager.GetString("CHM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose Action.
        /// </summary>
        public static string ChooseAction {
            get {
                return ResourceManager.GetString("ChooseAction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clear PDF.
        /// </summary>
        public static string ClearPdf {
            get {
                return ResourceManager.GetString("ClearPdf", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close.
        /// </summary>
        public static string Close {
            get {
                return ResourceManager.GetString("Close", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Closing....
        /// </summary>
        public static string closing {
            get {
                return ResourceManager.GetString("closing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Colors.
        /// </summary>
        public static string Colors {
            get {
                return ResourceManager.GetString("Colors", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Continue.
        /// </summary>
        public static string Continue {
            get {
                return ResourceManager.GetString("Continue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Control Before Evaluaton.
        /// </summary>
        public static string ControlBeforeEvaluaton {
            get {
                return ResourceManager.GetString("ControlBeforeEvaluaton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _(ConvertedFromWord).
        /// </summary>
        public static string ConvertedFromWord {
            get {
                return ResourceManager.GetString("ConvertedFromWord", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Correct.
        /// </summary>
        public static string Correct {
            get {
                return ResourceManager.GetString("Correct", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Count.
        /// </summary>
        public static string Count {
            get {
                return ResourceManager.GetString("Count", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cross recognition.
        /// </summary>
        public static string crossmethod {
            get {
                return ResourceManager.GetString("crossmethod", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date of last save.
        /// </summary>
        public static string Dateoflastsave {
            get {
                return ResourceManager.GetString("Dateoflastsave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Decide which fields are answered correctly.
        /// </summary>
        public static string Decidewhichfieldsareansweredcorrectly {
            get {
                return ResourceManager.GetString("Decidewhichfieldsareansweredcorrectly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Default Project Name.
        /// </summary>
        public static string DefaultProjectName {
            get {
                return ResourceManager.GetString("DefaultProjectName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete Page.
        /// </summary>
        public static string DeletePage {
            get {
                return ResourceManager.GetString("DeletePage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Document.
        /// </summary>
        public static string Document {
            get {
                return ResourceManager.GetString("Document", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Drag.
        /// </summary>
        public static string Drag {
            get {
                return ResourceManager.GetString("Drag", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to dddddddddd.
        /// </summary>
        public static string DragLeft {
            get {
                return ResourceManager.GetString("DragLeft", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Drag right.
        /// </summary>
        public static string DragRight {
            get {
                return ResourceManager.GetString("DragRight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit.
        /// </summary>
        public static string Edit {
            get {
                return ResourceManager.GetString("Edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit.
        /// </summary>
        public static string EditingEdit {
            get {
                return ResourceManager.GetString("EditingEdit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to EditingWin.
        /// </summary>
        public static string EditingWin {
            get {
                return ResourceManager.GetString("EditingWin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter your text.
        /// </summary>
        public static string Enteryourtext {
            get {
                return ResourceManager.GetString("Enteryourtext", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        public static string Error {
            get {
                return ResourceManager.GetString("Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not evaluate work number.
        /// </summary>
        public static string errorEvaluating {
            get {
                return ResourceManager.GetString("errorEvaluating", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Evaluate.
        /// </summary>
        public static string Evaluate {
            get {
                return ResourceManager.GetString("Evaluate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Evaluateing... Please wait.
        /// </summary>
        public static string EvaluateingWorks {
            get {
                return ResourceManager.GetString("EvaluateingWorks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Evaluate or open old.
        /// </summary>
        public static string EvaluateOrUseOld {
            get {
                return ResourceManager.GetString("EvaluateOrUseOld", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Evaluation.
        /// </summary>
        public static string Evaluation {
            get {
                return ResourceManager.GetString("Evaluation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Export.
        /// </summary>
        public static string Export {
            get {
                return ResourceManager.GetString("Export", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Files.
        /// </summary>
        public static string Files {
            get {
                return ResourceManager.GetString("Files", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fill of the whole square.
        /// </summary>
        public static string fillOfWholeSquare {
            get {
                return ResourceManager.GetString("fillOfWholeSquare", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Find.
        /// </summary>
        public static string Find {
            get {
                return ResourceManager.GetString("Find", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Font.
        /// </summary>
        public static string Font {
            get {
                return ResourceManager.GetString("Font", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to From Existing PDF.
        /// </summary>
        public static string FromExistingPDF {
            get {
                return ResourceManager.GetString("FromExistingPDF", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to From Word Document.
        /// </summary>
        public static string FromWordDocument {
            get {
                return ResourceManager.GetString("FromWordDocument", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to General.
        /// </summary>
        public static string General {
            get {
                return ResourceManager.GetString("General", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Grade.
        /// </summary>
        public static string Grade {
            get {
                return ResourceManager.GetString("Grade", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Help.
        /// </summary>
        public static string Help {
            get {
                return ResourceManager.GetString("Help", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to HTML.
        /// </summary>
        public static string HTML {
            get {
                return ResourceManager.GetString("HTML", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Image.
        /// </summary>
        public static string Image {
            get {
                return ResourceManager.GetString("Image", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Index.
        /// </summary>
        public static string Index {
            get {
                return ResourceManager.GetString("Index", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _JPEG.
        /// </summary>
        public static string JPEG {
            get {
                return ResourceManager.GetString("JPEG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Language.
        /// </summary>
        public static string Language {
            get {
                return ResourceManager.GetString("Language", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last Edit.
        /// </summary>
        public static string LastEdit {
            get {
                return ResourceManager.GetString("LastEdit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last Opened.
        /// </summary>
        public static string LastOpened {
            get {
                return ResourceManager.GetString("LastOpened", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LoadedScans.
        /// </summary>
        public static string LoadedScans {
            get {
                return ResourceManager.GetString("LoadedScans", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Local.
        /// </summary>
        public static string Local {
            get {
                return ResourceManager.GetString("Local", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Locators Length.
        /// </summary>
        public static string LocatorLength {
            get {
                return ResourceManager.GetString("LocatorLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Locators Margin.
        /// </summary>
        public static string LocatorMargin {
            get {
                return ResourceManager.GetString("LocatorMargin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Locators.
        /// </summary>
        public static string Locators {
            get {
                return ResourceManager.GetString("Locators", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Locators Color.
        /// </summary>
        public static string LocatorsColor {
            get {
                return ResourceManager.GetString("LocatorsColor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Locators Thickness.
        /// </summary>
        public static string LocatorThickness {
            get {
                return ResourceManager.GetString("LocatorThickness", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Locked.
        /// </summary>
        public static string Locked {
            get {
                return ResourceManager.GetString("Locked", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Minimize.
        /// </summary>
        public static string Minimize {
            get {
                return ResourceManager.GetString("Minimize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _More.
        /// </summary>
        public static string More {
            get {
                return ResourceManager.GetString("More", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to More Formats.
        /// </summary>
        public static string MoreFormats {
            get {
                return ResourceManager.GetString("MoreFormats", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        public static string Name {
            get {
                return ResourceManager.GetString("Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name Field.
        /// </summary>
        public static string Name_Field {
            get {
                return ResourceManager.GetString("Name Field", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name Field.
        /// </summary>
        public static string NameField {
            get {
                return ResourceManager.GetString("NameField", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Student Tester.
        /// </summary>
        public static string NameOfAplication {
            get {
                return ResourceManager.GetString("NameOfAplication", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name String.
        /// </summary>
        public static string NameString {
            get {
                return ResourceManager.GetString("NameString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _New.
        /// </summary>
        public static string New {
            get {
                return ResourceManager.GetString("New", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Page.
        /// </summary>
        public static string NewPage {
            get {
                return ResourceManager.GetString("NewPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No.
        /// </summary>
        public static string No {
            get {
                return ResourceManager.GetString("No", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No Project Loaded.
        /// </summary>
        public static string NoProjectLoaded {
            get {
                return ResourceManager.GetString("NoProjectLoaded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No Scans Loaded.
        /// </summary>
        public static string NoScansLoaded {
            get {
                return ResourceManager.GetString("NoScansLoaded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not able to load this file.
        /// </summary>
        public static string notabletoread {
            get {
                return ResourceManager.GetString("notabletoread", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not Decided.
        /// </summary>
        public static string NotDecided {
            get {
                return ResourceManager.GetString("NotDecided", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _NoTools.
        /// </summary>
        public static string NoTools {
            get {
                return ResourceManager.GetString("NoTools", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to not saved yet.
        /// </summary>
        public static string notsavedyet {
            get {
                return ResourceManager.GetString("notsavedyet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number.
        /// </summary>
        public static string Number {
            get {
                return ResourceManager.GetString("Number", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number of boxes.
        /// </summary>
        public static string Numberofboxes {
            get {
                return ResourceManager.GetString("Numberofboxes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number of pages.
        /// </summary>
        public static string Numberofpages {
            get {
                return ResourceManager.GetString("Numberofpages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number of questions.
        /// </summary>
        public static string Numberofquestions {
            get {
                return ResourceManager.GetString("Numberofquestions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number of text fields.
        /// </summary>
        public static string Numberoftextfields {
            get {
                return ResourceManager.GetString("Numberoftextfields", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OK.
        /// </summary>
        public static string OK {
            get {
                return ResourceManager.GetString("OK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _One.
        /// </summary>
        public static string One {
            get {
                return ResourceManager.GetString("One", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _One Paged.
        /// </summary>
        public static string OnePaged {
            get {
                return ResourceManager.GetString("OnePaged", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _One PNG to check.
        /// </summary>
        public static string OnePNGtocheck {
            get {
                return ResourceManager.GetString("OnePNGtocheck", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Open.
        /// </summary>
        public static string Open {
            get {
                return ResourceManager.GetString("Open", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open list of scans.
        /// </summary>
        public static string Openlistofscans {
            get {
                return ResourceManager.GetString("Openlistofscans", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open Project.
        /// </summary>
        public static string OpenProject {
            get {
                return ResourceManager.GetString("OpenProject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Original Doc.
        /// </summary>
        public static string OriginalDoc {
            get {
                return ResourceManager.GetString("OriginalDoc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Overview.
        /// </summary>
        public static string Overview {
            get {
                return ResourceManager.GetString("Overview", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Paths.
        /// </summary>
        public static string Paths {
            get {
                return ResourceManager.GetString("Paths", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PDF.
        /// </summary>
        public static string PDF {
            get {
                return ResourceManager.GetString("PDF", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PDF.
        /// </summary>
        public static string PDFfile {
            get {
                return ResourceManager.GetString("PDFfile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Percents.
        /// </summary>
        public static string Percents {
            get {
                return ResourceManager.GetString("Percents", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pictures.
        /// </summary>
        public static string Pictures {
            get {
                return ResourceManager.GetString("Pictures", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pictures (all readable).
        /// </summary>
        public static string Picturesallreadable {
            get {
                return ResourceManager.GetString("Picturesallreadable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _PNG.
        /// </summary>
        public static string PNG {
            get {
                return ResourceManager.GetString("PNG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Points.
        /// </summary>
        public static string Points {
            get {
                return ResourceManager.GetString("Points", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Print.
        /// </summary>
        public static string Print {
            get {
                return ResourceManager.GetString("Print", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Printer.
        /// </summary>
        public static string Printer {
            get {
                return ResourceManager.GetString("Printer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Printing.
        /// </summary>
        public static string Printing {
            get {
                return ResourceManager.GetString("Printing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Project.
        /// </summary>
        public static string Project {
            get {
                return ResourceManager.GetString("Project", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Project File Name.
        /// </summary>
        public static string ProjectFileName {
            get {
                return ResourceManager.GetString("ProjectFileName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Project Info.
        /// </summary>
        public static string ProjectInfo {
            get {
                return ResourceManager.GetString("ProjectInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Project Location.
        /// </summary>
        public static string ProjectLocation {
            get {
                return ResourceManager.GetString("ProjectLocation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Project.
        /// </summary>
        public static string ProjectName {
            get {
                return ResourceManager.GetString("ProjectName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Project version.
        /// </summary>
        public static string Projectversion {
            get {
                return ResourceManager.GetString("Projectversion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to question.
        /// </summary>
        public static string question {
            get {
                return ResourceManager.GetString("question", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Some works are already evaluated, do you want to evaluate again anyway?.
        /// </summary>
        public static string QuestionEvaluateOrUseOld {
            get {
                return ResourceManager.GetString("QuestionEvaluateOrUseOld", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Questions.
        /// </summary>
        public static string Questions {
            get {
                return ResourceManager.GetString("Questions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Read Scans.
        /// </summary>
        public static string Read {
            get {
                return ResourceManager.GetString("Read", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reading Scans.
        /// </summary>
        public static string ReadingScans {
            get {
                return ResourceManager.GetString("ReadingScans", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have loaded this many files:.
        /// </summary>
        public static string readingscansline1 {
            get {
                return ResourceManager.GetString("readingscansline1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to How many pages should each work have?.
        /// </summary>
        public static string readingscansline2 {
            get {
                return ResourceManager.GetString("readingscansline2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Works it will produce:.
        /// </summary>
        public static string readingscansline3 {
            get {
                return ResourceManager.GetString("readingscansline3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Leaving this many unused:.
        /// </summary>
        public static string readingscansline4 {
            get {
                return ResourceManager.GetString("readingscansline4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invert:.
        /// </summary>
        public static string readingscansline5 {
            get {
                return ResourceManager.GetString("readingscansline5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Realy return?.
        /// </summary>
        public static string RealyReturn {
            get {
                return ResourceManager.GetString("RealyReturn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reload.
        /// </summary>
        public static string Reload {
            get {
                return ResourceManager.GetString("Reload", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Results.
        /// </summary>
        public static string Results {
            get {
                return ResourceManager.GetString("Results", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Right Answer.
        /// </summary>
        public static string RightAnswer {
            get {
                return ResourceManager.GetString("RightAnswer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rigth / Evaluated.
        /// </summary>
        public static string RightOverAnswered {
            get {
                return ResourceManager.GetString("RightOverAnswered", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rotate.
        /// </summary>
        public static string Rotate {
            get {
                return ResourceManager.GetString("Rotate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rotate All.
        /// </summary>
        public static string RotateAll {
            get {
                return ResourceManager.GetString("RotateAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Save.
        /// </summary>
        public static string Save {
            get {
                return ResourceManager.GetString("Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Save As.
        /// </summary>
        public static string SaveAs {
            get {
                return ResourceManager.GetString("SaveAs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save As (Ctrl+Shift+S).
        /// </summary>
        public static string SaveAsCtrlShiftS {
            get {
                return ResourceManager.GetString("SaveAsCtrlShiftS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save (Ctrl+S).
        /// </summary>
        public static string SaveCtrlS {
            get {
                return ResourceManager.GetString("SaveCtrlS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Saved.
        /// </summary>
        public static string Saved {
            get {
                return ResourceManager.GetString("Saved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save PDF.
        /// </summary>
        public static string SavePDF {
            get {
                return ResourceManager.GetString("SavePDF", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Project is not saved.
        ///Do you want to save it?.
        /// </summary>
        public static string savequestion {
            get {
                return ResourceManager.GetString("savequestion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Scanner.
        /// </summary>
        public static string Scanner {
            get {
                return ResourceManager.GetString("Scanner", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You need to select first an scanner device from the list.
        /// </summary>
        public static string SelectScener {
            get {
                return ResourceManager.GetString("SelectScener", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Settings.
        /// </summary>
        public static string Settings {
            get {
                return ResourceManager.GetString("Settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to size of box.
        /// </summary>
        public static string sizeofbox {
            get {
                return ResourceManager.GetString("sizeofbox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to space between.
        /// </summary>
        public static string spacebetween {
            get {
                return ResourceManager.GetString("spacebetween", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Space Between Boxes.
        /// </summary>
        public static string spacebetweenBoxes {
            get {
                return ResourceManager.GetString("spacebetweenBoxes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Student Tester Projects.
        /// </summary>
        public static string StudentTesterProjects {
            get {
                return ResourceManager.GetString("StudentTesterProjects", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to succesfully scanned.
        /// </summary>
        public static string succesfullyscanned {
            get {
                return ResourceManager.GetString("succesfullyscanned", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Temp Folder.
        /// </summary>
        public static string TempFolder {
            get {
                return ResourceManager.GetString("TempFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to text.
        /// </summary>
        public static string text {
            get {
                return ResourceManager.GetString("text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Text Strings.
        /// </summary>
        public static string TextStrings {
            get {
                return ResourceManager.GetString("TextStrings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to English.
        /// </summary>
        public static string THIS_LANGUAGE {
            get {
                return ResourceManager.GetString("THIS LANGUAGE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Toogle Correct.
        /// </summary>
        public static string ToogleCorrect {
            get {
                return ResourceManager.GetString("ToogleCorrect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Undo Box.
        /// </summary>
        public static string UndoBox {
            get {
                return ResourceManager.GetString("UndoBox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Undo Field.
        /// </summary>
        public static string UndoField {
            get {
                return ResourceManager.GetString("UndoField", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Undo Name Field.
        /// </summary>
        public static string UndoNameField {
            get {
                return ResourceManager.GetString("UndoNameField", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Undo is not compatible
        /// with Delete Page.
        /// </summary>
        public static string UndoNotCompatible {
            get {
                return ResourceManager.GetString("UndoNotCompatible", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Undo Question.
        /// </summary>
        public static string UndoQuestion {
            get {
                return ResourceManager.GetString("UndoQuestion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unedited.
        /// </summary>
        public static string Unedited {
            get {
                return ResourceManager.GetString("Unedited", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Unload.
        /// </summary>
        public static string Unload {
            get {
                return ResourceManager.GetString("Unload", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unloaded.
        /// </summary>
        public static string unloaded {
            get {
                return ResourceManager.GetString("unloaded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Untitled.
        /// </summary>
        public static string Untitled {
            get {
                return ResourceManager.GetString("Untitled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use safe evaluation.
        /// </summary>
        public static string UseSafeEvaluation {
            get {
                return ResourceManager.GetString("UseSafeEvaluation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to version 1.0.0 (22/5).
        /// </summary>
        public static string version100 {
            get {
                return ResourceManager.GetString("version100", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _View.
        /// </summary>
        public static string View {
            get {
                return ResourceManager.GetString("View", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View Page.
        /// </summary>
        public static string ViewPage {
            get {
                return ResourceManager.GetString("ViewPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View scan.
        /// </summary>
        public static string ViewScan {
            get {
                return ResourceManager.GetString("ViewScan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Warning.
        /// </summary>
        public static string Warning {
            get {
                return ResourceManager.GetString("Warning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to One Name field is alredy added.
        ///would you like to move it here?.
        /// </summary>
        public static string WarningMoreThanOneNamefield {
            get {
                return ResourceManager.GetString("WarningMoreThanOneNamefield", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Warning: no Name Field added!.
        /// </summary>
        public static string WarningnoNameFieldadded {
            get {
                return ResourceManager.GetString("WarningnoNameFieldadded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to One or more works don&apos;t have enaught pages..
        /// </summary>
        public static string warningScansDontHaveEnaughtPages {
            get {
                return ResourceManager.GetString("warningScansDontHaveEnaughtPages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to width of bound.
        /// </summary>
        public static string widthofbound {
            get {
                return ResourceManager.GetString("widthofbound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to With Answers.
        /// </summary>
        public static string WithAnswers {
            get {
                return ResourceManager.GetString("WithAnswers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yes.
        /// </summary>
        public static string Yes {
            get {
                return ResourceManager.GetString("Yes", resourceCulture);
            }
        }
    }
}
