//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace _11_Image_Processing.Resources.Strings {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("_11_Image_Processing.Resources.Strings.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _AddBoxes.
        /// </summary>
        public static string AddBoxes {
            get {
                return ResourceManager.GetString("AddBoxes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Answer Boxes.
        /// </summary>
        public static string Answer_Boxes {
            get {
                return ResourceManager.GetString("Answer Boxes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _BlankPDFFile.
        /// </summary>
        public static string BlankPDFFile {
            get {
                return ResourceManager.GetString("BlankPDFFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Edit.
        /// </summary>
        public static string Edit {
            get {
                return ResourceManager.GetString("Edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Evaluate.
        /// </summary>
        public static string Evaluate {
            get {
                return ResourceManager.GetString("Evaluate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Export.
        /// </summary>
        public static string Export {
            get {
                return ResourceManager.GetString("Export", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Files.
        /// </summary>
        public static string Files {
            get {
                return ResourceManager.GetString("Files", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _FromExistingPDF.
        /// </summary>
        public static string FromExistingPDF {
            get {
                return ResourceManager.GetString("FromExistingPDF", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _FromWordDocument.
        /// </summary>
        public static string FromWordDocument {
            get {
                return ResourceManager.GetString("FromWordDocument", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Help.
        /// </summary>
        public static string Help {
            get {
                return ResourceManager.GetString("Help", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _JPEG.
        /// </summary>
        public static string JPEG {
            get {
                return ResourceManager.GetString("JPEG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name Field.
        /// </summary>
        public static string Name_Field {
            get {
                return ResourceManager.GetString("Name Field", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Student Tester.
        /// </summary>
        public static string NameOfAplication {
            get {
                return ResourceManager.GetString("NameOfAplication", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _New.
        /// </summary>
        public static string New {
            get {
                return ResourceManager.GetString("New", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _NoTools.
        /// </summary>
        public static string NoTools {
            get {
                return ResourceManager.GetString("NoTools", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _One.
        /// </summary>
        public static string One {
            get {
                return ResourceManager.GetString("One", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _OnePage.
        /// </summary>
        public static string OnePage {
            get {
                return ResourceManager.GetString("OnePage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Open.
        /// </summary>
        public static string Open {
            get {
                return ResourceManager.GetString("Open", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _PDF.
        /// </summary>
        public static string PDF {
            get {
                return ResourceManager.GetString("PDF", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Print.
        /// </summary>
        public static string Print {
            get {
                return ResourceManager.GetString("Print", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Read.
        /// </summary>
        public static string Read {
            get {
                return ResourceManager.GetString("Read", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Save.
        /// </summary>
        public static string Save {
            get {
                return ResourceManager.GetString("Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _SaveAs.
        /// </summary>
        public static string SaveAs {
            get {
                return ResourceManager.GetString("SaveAs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Scanner.
        /// </summary>
        public static string Scanner {
            get {
                return ResourceManager.GetString("Scanner", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Settings.
        /// </summary>
        public static string Settings {
            get {
                return ResourceManager.GetString("Settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Unload.
        /// </summary>
        public static string Unload {
            get {
                return ResourceManager.GetString("Unload", resourceCulture);
            }
        }
    }
}
